# Generated by Django 4.1.3 on 2024-01-09 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsaleapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointofsaleapi.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointofsaleapi.order')),
            ],
        ),
    ]
