# Generated by Django 4.1.3 on 2024-01-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointofsaleapi', '0005_alter_revenue_tip_alter_revenue_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='order',
            field=models.IntegerField(),
        ),
    ]
